### ISSUE TITLE
Can you provide the code to collect the dataset? We are trying to collect a video version

### ISSUE THREAD

**Issue by chenzhutian** [luyangzhu/NBA2K-dataset#3]
Hi! Thanks for the great work!
Can you provide the code to collect the dataset? 
We are trying to collect a video version

Many thanks!

**Comment by luyangzhu** [comment]
Hi, Thanks for your interest in our work!
Unfortunately, we can not release the code for data collection due to the license issue.
Maybe you can check examples provided by RenderDoc: https://renderdoc.org/docs/python_api/examples/renderdoc/index.html
Our code is modified based on that. I think those examples should be a good starting point.

**Comment by chenzhutian** [comment]
Awesome! Thanks for your reply!
